# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  tox:
    docker:
      - image: themattrix/tox-base
        user: root
      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: hobbit_core

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: sleep 10
      - run:
          command: tox
  test-py36:
    docker:
      - image: circleci/python:3.6
        user: root
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install flake8 pytest pytest-cov pytest-env
            pip install --editable .
            pip install celery mypy_extensions
      - run:
          name: use flake8 check self
          command: flake8 .
      - run:
          name: run hobbit cmd
          command: hobbit --echo startproject -n demo -d ~/haha -f --example -p 1024 --no-celery
      - run:
          name: tree flask project
          command: |
            cd ~/haha
            apt-get install -y tree
            tree
      - run:
          name: run tests
          command: |
            cd ~/haha
            flask db init && flask db migrate && flask db upgrade
            flake8 . --exclude migrations
            py.test
  test-py37:
    docker:
      - image: circleci/python:3.7
        user: root
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install flake8 pytest pytest-cov pytest-env
            pip install --editable .
            pip install celery mypy_extensions
      - run:
          name: use flake8 check self
          command: flake8 .
      - run:
          name: run hobbit cmd
          command: |
            mkdir ~/haha && cd ~/haha
            hobbit --echo startproject -n demo -f --example -p 1024 --celery
      - run:
          name: tree flask project
          command: |
            cd ~/haha
            apt-get install -y tree
            tree
      - run:
          name: run tests
          command: |
            cd ~/haha
            flask db init && flask db migrate && flask db upgrade
            flake8 . --exclude migrations
            py.test

workflows:
  version: 2
  test:
    jobs:
      - tox
      - test-py36:
          requires:
            - tox
      - test-py37:
          requires:
            - tox
