# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  tox:
    docker:
      - image: circleci/python:3.6
        user: root
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies && tox
          command: |
            curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
            export PATH="/root/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            pyenv install 3.7.0
            pyenv virtualenv -f 3.7.0 py37
            pyenv shell py37
            pip install tox
            tox
  test-py36:
    docker:
      - image: circleci/python:3.6
        user: root
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install flake8 pytest pytest-cov
            pip install --editable .
      - run:
          name: use flake8 check self
          command: |
            flake8 .
      - run:
          name: run hobbit cmd
          command: |
            hobbit  --echo startproject -n demo -d ~/haha -f
      - run:
          name: tree flask project
          command: |
            cd ~/haha
            apt-get install -y tree
            tree
      - run:
          name: run tests
          environment:
            FLASK_APP: app/run.py
            FLASK_ENV: testing
          command: |
            cd ~/haha
            flask db init && flask db migrate && flask db upgrade
            flake8 . --exclude migrations
            py.test --cov . --cov-report term-missing -s
  test-py37:
    docker:
      - image: circleci/python:3.7
        user: root
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install flake8 pytest pytest-cov
            pip install --editable .
      - run:
          name: use flake8 check self
          command: |
            flake8 .
      - run:
          name: run hobbit cmd
          command: |
            mkdir ~/haha && cd ~/haha
            hobbit  --echo startproject -n demo -f
      - run:
          name: tree flask project
          command: |
            cd ~/haha
            apt-get install -y tree
            tree
      - run:
          name: run tests
          environment:
            FLASK_APP: app/run.py
            FLASK_ENV: testing
          command: |
            cd ~/haha
            flask db init && flask db migrate && flask db upgrade
            flake8 . --exclude migrations
            py.test --cov . --cov-report term-missing -s

workflows:
  version: 2
  test:
    jobs:
      - tox
      - test-py36:
          requires:
            - tox
      - test-py37:
          requires:
            - tox
